group_imports = "StdExternalCrate"
imports_granularity = "Crate"
format_code_in_doc_comments = true
hard_tabs = true
max_width = 80
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
